<?php
/**
 * Created by PhpStorm.
 * User: uho0613
 * Date: 06.07.19
 * Time: 2:26
 */

namespace MyModules\QuickOrder\Model\ResourceModel;
use Magento\Framework\Exception\LocalizedException;

use MyModules\QuickOrder\Api\Order\QuickOrderInterface;



class Status  extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /** {@inheritdoc} */
    protected function _construct()
    {
        $this->_init(\MyModules\QuickOrder\Api\Status\StatusInterface::TABLE_NAME, \MyModules\QuickOrder\Api\Status\StatusInterface::ID_FIELD);
    }

    public function _beforeDelete(\Magento\Framework\Model\AbstractModel $object)
    {
        if($object->getId() == 1){
            throw new LocalizedException(__('Status deleted can not deleted'));
        }
        return parent::_beforeDelete($object); // TODO: Change the autogenerated stub
    }

    public function _afterDelete(\Magento\Framework\Model\AbstractModel $object)
    {
        // when status was deleted, order which had this status chanche status to deleted status whith id = 1

        $table = $this->getTable(QuickOrderInterface::TABLE_NAME);
        $where = ['status = ?' => $object->getId()];
        $bind = ['status' => 1];
        $this->getConnection()->update($table, $bind ,$where);
        return parent::_afterDelete($object); // TODO: Change the autogenerated stub
    }
}