<?php
/**
 * Created by PhpStorm.
 * User: uho0613
 * Date: 06.07.19
 * Time: 2:26
 */

namespace MyModules\QuickOrder\Model\ResourceModel;
use Magento\Framework\Exception\LocalizedException;

use MyModules\QuickOrder\Api\Order\QuickOrderInterface;



class Status  extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    protected $scopeConfig;
    protected $messageManager;

    public function __construct(
        \Magento\Framework\Message\ManagerInterface $messageManager,
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        \Magento\Framework\Model\ResourceModel\Db\Context $context,
        $connectionName = null)
    {
        $this->messageManager = $messageManager;
        $this->scopeConfig  =  $scopeConfig;
        parent::__construct($context, $connectionName);
    }

    /** {@inheritdoc} */
    protected function _construct()
    {
        $this->_init(\MyModules\QuickOrder\Api\Status\StatusInterface::TABLE_NAME, \MyModules\QuickOrder\Api\Status\StatusInterface::ID_FIELD);
    }

    /**
     * @param \Magento\Framework\Model\AbstractModel $object
     * @return \Magento\Framework\Model\ResourceModel\Db\AbstractDb
     * @throws LocalizedException
     */
    public function _beforeDelete(\Magento\Framework\Model\AbstractModel $object)
    {
        $id = $object->getId();
        if( $id== 1 || $id == $this->statusDefault()){
            $this->messageManager->addWarningMessage("Statuses -deleted- and -default- can't be deleted");
            throw new LocalizedException(__('Status deleted can not deleted'));
        }
        return parent::_beforeDelete($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Magento\Framework\Model\AbstractModel $object
     * @return \Magento\Framework\Model\ResourceModel\Db\AbstractDb
     */
    public function _afterDelete(\Magento\Framework\Model\AbstractModel $object)
    {
        // when status was deleted, order which had this status chanche status to deleted status whith id = 1

        $table = $this->getTable(QuickOrderInterface::TABLE_NAME);
        $where = ['status = ?' => $object->getId()];
        $bind = ['status' => 1];
        $this->getConnection()->update($table, $bind ,$where);
        return parent::_afterDelete($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return int
     */
    public function statusDefault()
    {
        $storeTipe = \Magento\Store\Model\ScopeInterface::SCOPE_WEBSITE;
        $path = 'my_quick_orders/general/default_status';
        return $this->scopeConfig->getValue($path,$storeTipe);

    }
}